# Generated by Django 5.0.6 on 2024-07-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='upload_to',
            new_name='updated_at',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
    ]
